# Build Docker image for this app, to be published to Docker Registry
pool:
  vmImage: 'ubuntu-16.04'
variables:
  buildConfiguration: 'Release'
steps:
- script: |
    docker build -f Dockerfile.build -t dotnetcore-build:$BUILD_BUILDID .
    docker run -v $(System.DefaultWorkingDirectory):/testresults --name dotnetcoreapp --rm dotnetcore-build:$BUILD_BUILDID

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true

