# Build and run tests inside the docker container
FROM microsoft/dotnet:2.2-sdk
WORKDIR /app
# copy the contents of agent working directory on host to workdir in container
COPY . ./
# dotnet commands to build, test, and publish

WORKDIR /app/tests
RUN dotnet test dotnetcore-tests/dotnetcore-tests.csproj -c Release --logger "trx;LogFileName=testresults.trx"

WORKDIR /app/src
RUN dotnet publish -c Release -o out
ENTRYPOINT dotnet out/pipelines-dotnet-core.dll
