# Build and run tests inside the docker container
FROM microsoft/dotnet:2.2-sdk
WORKDIR /app
# copy the contents of agent working directory on host to workdir in container
COPY . ./
# dotnet commands to build, test, and publish

#ENTRYPOINT ["dotnet", "test", "dotnetcore-tests/dotnetcore-tests.csproj" "--logger:trx", "--results-directory", "/testresults"]
ENTRYPOINT ["/bin/bash", "/app/run.sh"]
#ENTRYPOINT ["/bin/bash"]